spring.application.name=productos
server.port=8081
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:oracle:thin:@localhost:1521/FREEPDB1}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:PRODUCTOS}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:productos123}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.open-in-view=false
spring.sql.init.mode=never
