spring.application.name=gateway
server.port=8080

connectshop.services.productos=${PRODUCTOS_SERVICE_URL:http://localhost:8081}
connectshop.services.usuarios=${USUARIOS_SERVICE_URL:http://localhost:8082}
connectshop.services.pedidos=${PEDIDOS_SERVICE_URL:http://localhost:8083}
connectshop.services.inventario=${INVENTARIO_SERVICE_URL:http://localhost:8084}
connectshop.services.pagos=${PAGOS_SERVICE_URL:http://localhost:8085}

springdoc.swagger-ui.urls[0].name=Productos
springdoc.swagger-ui.urls[0].url=/docs/productos
springdoc.swagger-ui.urls[1].name=Usuarios
springdoc.swagger-ui.urls[1].url=/docs/usuarios
springdoc.swagger-ui.urls[2].name=Pedidos
springdoc.swagger-ui.urls[2].url=/docs/pedidos
springdoc.swagger-ui.urls[3].name=Inventario
springdoc.swagger-ui.urls[3].url=/docs/inventario
springdoc.swagger-ui.urls[4].name=Pagos
springdoc.swagger-ui.urls[4].url=/docs/pagos
springdoc.swagger-ui.disable-swagger-default-url=true
