CREATE USER PRODUCTOS IDENTIFIED BY productos123;
GRANT CREATE SESSION, RESOURCE TO PRODUCTOS;
ALTER USER PRODUCTOS QUOTA UNLIMITED ON USERS;

CREATE USER USUARIOS IDENTIFIED BY usuarios123;
GRANT CREATE SESSION, RESOURCE TO USUARIOS;
ALTER USER USUARIOS QUOTA UNLIMITED ON USERS;

CREATE USER PEDIDOS IDENTIFIED BY pedidos123;
GRANT CREATE SESSION, RESOURCE TO PEDIDOS;
ALTER USER PEDIDOS QUOTA UNLIMITED ON USERS;

CREATE USER INVENTARIO IDENTIFIED BY inventario123;
GRANT CREATE SESSION, RESOURCE TO INVENTARIO;
ALTER USER INVENTARIO QUOTA UNLIMITED ON USERS;

CREATE USER PAGOS IDENTIFIED BY pagos123;
GRANT CREATE SESSION, RESOURCE TO PAGOS;
ALTER USER PAGOS QUOTA UNLIMITED ON USERS;
