spring.application.name=pedidos
server.port=8083
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:h2:mem:pedidosdb}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.h2.Driver}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sa}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.jpa.database-platform=${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.H2Dialect}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.open-in-view=false
spring.sql.init.mode=never
spring.h2.console.enabled=true
connectshopp.services.usuarios.url=${USUARIOS_SERVICE_URL:http://localhost:8082}
connectshopp.services.productos.url=${PRODUCTOS_SERVICE_URL:http://localhost:8081}
connectshopp.services.inventario.url=${INVENTARIO_SERVICE_URL:http://localhost:8084}
connectshopp.services.pagos.url=${PAGOS_SERVICE_URL:http://localhost:8085}
