spring.application.name=pedidos
server.port=8083
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:oracle:thin:@localhost:1521/FREEPDB1}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:PEDIDOS}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:pedidos123}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.open-in-view=false
spring.sql.init.mode=never
connectshopp.services.usuarios.url=${USUARIOS_SERVICE_URL:http://localhost:8082}
connectshopp.services.productos.url=${PRODUCTOS_SERVICE_URL:http://localhost:8081}
connectshopp.services.inventario.url=${INVENTARIO_SERVICE_URL:http://localhost:8084}
connectshopp.services.pagos.url=${PAGOS_SERVICE_URL:http://localhost:8085}
